Excel xlsx file; not supported

Traceback (most recent call last):
  File "task.py", line 116, in main
    _run()
  File "task.py", line 107, in _run
    roller.download_remote_files()
  File "task.py", line 46, in download_remote_files
    self._cases = self._download_remote_excel_file('Cases and Deaths by County by Date')
  File "task.py", line 50, in _download_remote_excel_file
    df = read_excel(self._get_remote_excel_file_url(link_text))
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/pandas/util/_decorators.py", line 296, in wrapper
    return func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 304, in read_excel
    io = ExcelFile(io, engine=engine)
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 867, in __init__
    self._reader = self._engines[engine](self._io)
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/pandas/io/excel/_xlrd.py", line 22, in __init__
    super().__init__(filepath_or_buffer)
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 351, in __init__
    self.book = self.load_workbook(filepath_or_buffer)
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/pandas/io/excel/_xlrd.py", line 35, in load_workbook
    return open_workbook(file_contents=data)
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/xlrd/__init__.py", line 170, in open_workbook
    raise XLRDError(FILE_FORMAT_DESCRIPTIONS[file_format]+'; not supported')
xlrd.biffh.XLRDError: Excel xlsx file; not supported
